config/routes.rb
DinnerTyme::Application.routes.draw do
  resources :ingredients

  resources :recipes

  resources :kitchens

  root :to => 'kitchens#index'

end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  unit       :string(255)
#  amount     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :amount, :name, :unit, :recipe_ids
  has_and_belongs_to_many :recipes
end

app/models/kitchen.rb
# == Schema Information
#
# Table name: kitchens
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Kitchen < ActiveRecord::Base
  attr_accessible :name, :recipe_ids
  has_many :recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  steps      :text
#  photo      :string(255)
#  serves     :integer
#  rating     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  kitchen_id :integer
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :photo, :rating, :serves, :steps, :kitchen_id, :ingredient_ids
  belongs_to :kitchen
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  # GET /kitchens
  # GET /kitchens.json
  def index
    @kitchens = Kitchen.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kitchens }
    end
  end

  # GET /kitchens/1
  # GET /kitchens/1.json
  def show
    @kitchen = Kitchen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kitchen }
    end
  end

  # GET /kitchens/new
  # GET /kitchens/new.json
  def new
    @kitchen = Kitchen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kitchen }
    end
  end

  # GET /kitchens/1/edit
  def edit
    @kitchen = Kitchen.find(params[:id])
  end

  # POST /kitchens
  # POST /kitchens.json
  def create
    @kitchen = Kitchen.new(params[:kitchen])

    respond_to do |format|
      if @kitchen.save
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully created.' }
        format.json { render json: @kitchen, status: :created, location: @kitchen }
      else
        format.html { render action: "new" }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kitchens/1
  # PUT /kitchens/1.json
  def update
    @kitchen = Kitchen.find(params[:id])

    respond_to do |format|
      if @kitchen.update_attributes(params[:kitchen])
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchens/1
  # DELETE /kitchens/1.json
  def destroy
    @kitchen = Kitchen.find(params[:id])
    @kitchen.destroy

    respond_to do |format|
      format.html { redirect_to kitchens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :unit %>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>
  
  <br>
  
  <div class="field">
      Used in:
	  <% Recipe.all.each do |recipe| %>
	    <%= recipe.name %>
	    <%= check_box_tag 'ingredient[recipe_ids][]', recipe.id, @ingredient.recipes.include?(recipe) %>
	  <% end %>  
  </div>
  
  <br>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<div class="wrapper">
	
	<% @ingredients.each do |ingredient| %>
	    Name: <%= ingredient.name %><br>
	    Unit: <%= ingredient.unit %><br>
	    Amount: <%= ingredient.amount %><br>
	    <%= link_to 'Show', ingredient %>
	    <%= link_to 'Edit', edit_ingredient_path(ingredient) %>
	    <%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %>
		<br><br>
	<% end %>
	
</div>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ingredient.name %>
</p>

<p>
  <b>Unit:</b>
  <%= @ingredient.unit %>
</p>

<p>
  <b>Amount:</b>
  <%= @ingredient.amount %>
</p>

<p>
  <b>Used in:</b>
  <% Recipe.all.each do |recipe| %>
	<%= recipe.name %>
	<%= check_box_tag 'ingredient[recipe_ids][]', recipe.id, @ingredient.recipes.include?(recipe) %>
  <% end %>  
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/kitchens/_form.html.erb
<%= form_for(@kitchen) do |f| %>
  <% if @kitchen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitchen.errors.count, "error") %> prohibited this kitchen from being saved:</h2>

      <ul>
      <% @kitchen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <% Recipe.all.each do |recipe| %>
  	<%= recipe.name %>
  	<%= check_box_tag "kitchen[recipe_ids][]", recipe.id, @kitchen.recipes.include?(recipe) %>
  <% end %>
  
  <br><br>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kitchens/edit.html.erb
<h1>Editing kitchen</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitchen %> |
<%= link_to 'Back', kitchens_path %>

app/views/kitchens/index.html.erb
<h1>Kitchens</h1>

<div class="wrapper">
	
	<% @kitchens.each do |kitchen| %>
		<%= kitchen.name %>
		<%= link_to 'Show', kitchen %>
		<%= link_to 'Edit', edit_kitchen_path(kitchen) %>
		<%= link_to 'Destroy', kitchen, method: :delete, data: { confirm: 'Are you sure?' } %>
		<br>
	<% end %>
	
</div>

<br />

<%= link_to 'New Kitchen', new_kitchen_path %>

app/views/kitchens/new.html.erb
<h1>New kitchen</h1>

<%= render 'form' %>

<%= link_to 'Back', kitchens_path %>

app/views/kitchens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @kitchen.name %>
</p>


<%= link_to 'Edit', edit_kitchen_path(@kitchen) %> |
<%= link_to 'Back', kitchens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DinnerTyme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
	  <div class="navbar-inner"> 
	    <div class="container">	    
	      <%= link_to "DinnerTyme", root_path, :class=>"brand" %>
	      <div class="nav-collapse collapse">
	        <ul class="nav">
	          <li><%= link_to "Kitchens", kitchens_path %></li>
	          <li><%= link_to "Recipes", recipes_path %></li>
	          <li><%= link_to "Ingredients", ingredients_path %></li>              
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>	
	
	<br>
	<br>
	<br>
	
	<div class="container">
		<%= yield %>
	</div>

	
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :kitchen_id %>
    <%= f.select :kitchen_id, Kitchen.all.map{|k| [k.name, k.id]}, {:prompt=>"Pick a kitchen"} %>
  </div>  
  
  <div class="field">
  	Ingredients:
  	<p>
	  <% Ingredient.all.each do |ingredient| %>
	    <%= ingredient.name %>
	    <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, @recipe.ingredients.include?(ingredient) %>
	  <% end %>  
	<p>
  </div>
  
  <div class="field">
    <%= f.label :steps %>
    <%= f.text_area :steps %>
  </div>
  <div class="field">
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :serves %>
    <%= f.number_field :serves %>
  </div>
  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<div class="wrapper">

	<div class="element">
	
	<% @recipes.each do |recipe| %>
		<%= recipe.photo ? image_tag(recipe.photo) : "(no photo)" %><br>
	    Recipe Name: <%= recipe.name %><br>
	   	Rating: <%= recipe.rating %><br> 
	    Kitchen: <%= recipe.kitchen.name %><br>
	    Serves: <%= recipe.serves %><br>
	    Steps: <%= recipe.steps %><br>
	    <%= link_to 'Show', recipe %>
	    <%= link_to 'Edit', edit_recipe_path(recipe) %>
	    <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
	    <br><br>
	<% end %>

	</div>
	
</div>


<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
</p>

<p>
  <b>Kitchen:</b>
  <%= @recipe.kitchen.name %>
</p>

<p>
  <b>Ingredients:</b>
  <% Ingredient.all.each do |ingredient| %>
	<%= ingredient.name %>
	<%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, @recipe.ingredients.include?(ingredient) %>
  <% end %>  
</p>

<p>
  <b>Steps:</b>
  <%= @recipe.steps %>
</p>

<p>
  <b>Photo:</b>
  <%= @recipe.photo %>
</p>

<p>
  <b>Serves:</b>
  <%= @recipe.serves %>
</p>

<p>
  <b>Rating:</b>
  <%= @recipe.rating %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>